apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::040201632714:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CB2OL28BGX9Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      - system:nodes
      rolearn: arn:aws:iam::040201632714:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-06T05:53:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1730"
  uid: c2e26328-feeb-416c-87aa-e89de3615b1e
